#! /bin/bash

# get config
echo "Your admin name?"
read ADMIN_ACCOUNT
echo "Serial number of computer?"
read HOSTNAME

#curl --proto '=https' --tlsv1.2 -sSf https://raw.github.com/whatever | sh
gpm -m /dev/input/mice -t imps2
timedatectl set-ntp true

# we can pipe cmds to fdisk but I can't remember the entire cmd chain
# don't execute this until we check it (it is wrong)
echo -e "g\nn\n\n\n\nw" | fdisk -w always /dev/sda

#fdisk /dev/sda
#- delete all partitions
#- create 1 linux system partition that uses the whole disk

echo -e "g\nn\n\n\n+300M\nt\n1\nn\n\n\n+16G\nt\n\n19\nn\n\n\n\nw" | fdisk /dev/nvme0n1
# fdisk /dev/nvme0n1
# - delete all partitions
# - create 1 efi system partition that uses +300M
# - create 1 linux swap partition that uses +16G
# - create 1 linux system partition that uses the rest of the disk

mkfs.ext4 /dev/nvme0n1p3
mkfs.vfat -F32  /dev/nvme0n1p1
mkswap /dev/nvme0n1p2
swapon /dev/nvme0n1p2
mount /dev/nvme0n1p3 /mnt
mkdir -p /mnt/{boot/efi,home}
mount /dev/nvme0n1p1 /mnt/boot/efi
mount /dev/sda1 /mnt/home


# I feel that we can cat this mirror list
# * 3 (Installing basic packages)
echo "Server = http://mirror.aarnet.edu.au/pub/archlinux/\$repo/os/\$arch" > /etc/pacman.d/mirrorlist
#vim /etc/pacman.d/mirrorlist
# (Change the mirrorlist to `Server = http://mirror.arrnet.edu.au/pub/archlinux/$repo/os/$arch`)

# * 3.1
pacstrap /mnt base base-devel linux linux-firmware xorg-server sddm plasma-desktop arduino git python3 dotnet-runtime dotnet-sdk networkmanager dhcpcd sudo kde-applications firefox terminator vim nano code ntfs-3g nfs-utils freeradius
# (you have to wait for pacman to exit on a error for some reason to run the next command then run the install again)
pacman-key --init && pacman-key --populate archlinux
pacstrap /mnt base base-devel linux linux-firmware xorg-server sddm plasma-desktop arduino git python3 dotnet-runtime dotnet-sdk networkmanager dhcpcd sudo kde-applications firefox terminator vim nano code ntfs-3g nfs-utils freeradius

# * 3.2
genfstab -U /mnt >> /mnt/etc/fstab
cat << EOF > /mnt/strap.sh
#! /bin/bash

# * 4 (Inside chroot)
ln -sf /usr/share/zoneinfo/Australia/Canberra /etc/localtime
hwclock --systohc

# is this right?
echo -n "LANG=en_AU.UTF-8" > /etc/default/locale
# vim /etc/locale.gen
# (uncomment the line that says `en_AU.UTF-8 UTF-8`)

echo -e 'LANG=en_AU.UTF-8' > /etc/locale.conf
# vim /etc/locale.conf
# (add `LANG=en_AU.UTF-8`)
locale-gen

# is this right? 
echo $HOSTNAME > /etc/hostname

# * 4.1
systemctl enable NetworkManager
systemctl enable dhcpcd
systemctl enable sddm

# * 5 (Add the user)
useradd -m user
useradd -mG wheel lockness
useradd -mG wheel carteras
useradd -mG wheel woobi3
# is this right? 
echo -n "user:user" | chpasswd
# is this right? 
echo Admin passsword input
passwd $ADMIN_ACCOUNT

# * 5.1
#visudo
echo "%wheel ALL=(ALL:ALL) ALL" >> /etc/sudoers
# (uncomment line 85)

# * 5.2
cd /opt
git clone https://aur.archlinux.org/yay.git
cd yay/
vim /etc/makepkg.conf
# (set `MAKEFLAGS="-j2"` to `MAKEFLAGS="-j12"`)
chown -R $ADMIN_ACCOUNT: .
sudo -u $ADMIN_ACCOUNT makepkg -sci
sudo -u $ADMIN_ACCOUNT yay -S hfsprogs

* 5.3
pacman --noconfirm -S grub efibootmgr
grub-install --taget=x86_64-efi --efi-directory=/boot/efi/
grub-mkconfig -o /boot/grub/grub.cfg
EOF
#this pause is for debugging
read 
arch-chroot /mnt "/bin/bash /strap.sh"


* 6 (Finish up)
umount -R /mnt
